const responseBank = {

  greeting: {
    casual: [
      { id: "greet_cas_1", text: "Hey there! How's it going?" },
      { id: "greet_cas_2", text: "Hi! What's on your mind?" },
      { id: "greet_cas_3", text: "Hey! Good to see you. What can I help with?" },
      { id: "greet_cas_4", text: "What's up? I'm here if you need anything." },
      { id: "greet_cas_5", text: "Hey hey! What brings you here today?" },
      { id: "greet_cas_6", text: "Yo! What can I do for you?" },
      { id: "greet_cas_7", text: "Hi there! How can I help?" },
      { id: "greet_cas_8", text: "Hey! Ready when you are." },
      { id: "greet_cas_9", text: "What's going on? Let me know how I can help." },
      { id: "greet_cas_10", text: "Hi! Nice to chat. What's up?" },
    ],
    formal: [
      { id: "greet_for_1", text: "Hello! How can I assist you today?" },
      { id: "greet_for_2", text: "Good day. How may I help you?" },
      { id: "greet_for_3", text: "Welcome. I'm here to help — what do you need?" },
      { id: "greet_for_4", text: "Hello there. What can I do for you?" },
      { id: "greet_for_5", text: "Greetings. Let me know how I can be of assistance." },
      { id: "greet_for_6", text: "Good to hear from you. How may I assist?" },
      { id: "greet_for_7", text: "Hello. I'm at your service — what do you need help with?" },
      { id: "greet_for_8", text: "Welcome. Please let me know how I can help you today." },
      { id: "greet_for_9", text: "Hello, and thank you for reaching out. What can I help with?" },
      { id: "greet_for_10", text: "Good day. I'm ready to assist you with whatever you need." },
    ],
    returning: [
      { id: "greet_ret_1", text: "Welcome back! What can I help with this time?" },
      { id: "greet_ret_2", text: "Hey, good to see you again! What's up?" },
      { id: "greet_ret_3", text: "Back again! How can I help?" },
      { id: "greet_ret_4", text: "Oh hey, welcome back! What are we working on?" },
      { id: "greet_ret_5", text: "Good to see you again. What can I do for you this time?" },
      { id: "greet_ret_6", text: "You're back! Ready to dive in — what do you need?" },
      { id: "greet_ret_7", text: "Hey again! What's on the agenda?" },
      { id: "greet_ret_8", text: "Welcome back. Let me know what you need." },
      { id: "greet_ret_9", text: "Nice to see you again! How can I help?" },
      { id: "greet_ret_10", text: "Back for more? I'm here. What's up?" },
    ],
  },

  farewell: {
    casual: [
      { id: "bye_cas_1", text: "See ya! Take care." },
      { id: "bye_cas_2", text: "Later! Hope that helped." },
      { id: "bye_cas_3", text: "Catch you later! Let me know if anything else comes up." },
      { id: "bye_cas_4", text: "Alright, take it easy!" },
      { id: "bye_cas_5", text: "Peace out! Come back anytime." },
      { id: "bye_cas_6", text: "See you around! Hope I was useful." },
      { id: "bye_cas_7", text: "Bye! Don't be a stranger." },
      { id: "bye_cas_8", text: "Later! Hit me up if you need anything." },
      { id: "bye_cas_9", text: "Take care! Always happy to chat." },
      { id: "bye_cas_10", text: "Alright, catch you next time!" },
    ],
    formal: [
      { id: "bye_for_1", text: "Thank you for reaching out. Have a great day." },
      { id: "bye_for_2", text: "Glad I could help. Don't hesitate to come back." },
      { id: "bye_for_3", text: "Take care. Feel free to reach out anytime." },
      { id: "bye_for_4", text: "It was a pleasure assisting you. Goodbye." },
      { id: "bye_for_5", text: "Thank you for your time. I hope I was helpful." },
      { id: "bye_for_6", text: "Have a wonderful day. Don't hesitate to return if you need anything." },
      { id: "bye_for_7", text: "I'm glad I could assist. Wishing you all the best." },
      { id: "bye_for_8", text: "Thank you. Please reach out whenever you need help." },
      { id: "bye_for_9", text: "Goodbye, and best of luck with everything." },
      { id: "bye_for_10", text: "It was great helping you. Take care and have a good one." },
    ],
  },

  gratitude: {
    casual: [
      { id: "thx_cas_1", text: "No problem at all! Happy to help." },
      { id: "thx_cas_2", text: "Anytime! That's what I'm here for." },
      { id: "thx_cas_3", text: "You got it! Let me know if you need anything else." },
      { id: "thx_cas_4", text: "Glad that worked out!" },
      { id: "thx_cas_5", text: "Sure thing! Always happy to help." },
      { id: "thx_cas_6", text: "No worries! Glad I could help out." },
      { id: "thx_cas_7", text: "Hey, that's why I'm here! Anything else?" },
      { id: "thx_cas_8", text: "Of course! It was a fun one." },
      { id: "thx_cas_9", text: "Happy to! Hit me up anytime." },
      { id: "thx_cas_10", text: "Not a problem. I enjoyed helping!" },
    ],
    formal: [
      { id: "thx_for_1", text: "You're very welcome. I'm glad I could assist." },
      { id: "thx_for_2", text: "Happy to help. Please don't hesitate to ask again." },
      { id: "thx_for_3", text: "It's my pleasure. Let me know if there's anything else." },
      { id: "thx_for_4", text: "I'm glad I could be of help. Thank you for reaching out." },
      { id: "thx_for_5", text: "You're welcome. It was my pleasure to assist." },
      { id: "thx_for_6", text: "I appreciate your kind words. I'm here whenever you need me." },
      { id: "thx_for_7", text: "Thank you. I'm glad the information was useful." },
      { id: "thx_for_8", text: "You're very welcome. I'm always here to help." },
      { id: "thx_for_9", text: "It was no trouble at all. Please reach out anytime." },
      { id: "thx_for_10", text: "I'm pleased I could help. Don't hesitate to come back." },
    ],
  },

  question_knowledge: {
    weather: [
      { id: "q_wea_1", text: "I don't have live weather data, but I'd recommend checking a weather app or site for the latest forecast." },
      { id: "q_wea_2", text: "Weather isn't really my area — try a weather service for up-to-date info!" },
      { id: "q_wea_3", text: "I can't check the weather for you, but your phone's weather app should have you covered." },
      { id: "q_wea_4", text: "I wish I could tell you, but I don't have access to real-time weather data. Try a weather app!" },
      { id: "q_wea_5", text: "Unfortunately I can't look up weather. Your best bet is a weather service or app." },
      { id: "q_wea_6", text: "No live data on my end, but a quick search or weather app should get you sorted." },
      { id: "q_wea_7", text: "I'd love to help with that, but weather isn't something I can check. Try your phone's weather widget!" },
      { id: "q_wea_8", text: "Can't do weather lookups, but any weather app will have exactly what you need." },
      { id: "q_wea_9", text: "Real-time data is outside my capabilities. For weather, I'd point you to a dedicated service." },
      { id: "q_wea_10", text: "I don't have weather access, sorry! A weather app or a quick web search will do the trick." },
    ],
    time: [
      { id: "q_tim_1", text: "I don't have access to a clock, but your device should show the current time." },
      { id: "q_tim_2", text: "I can't tell time on my own — check your taskbar or phone!" },
      { id: "q_tim_3", text: "No clock on my end! Your device's clock is your best bet." },
      { id: "q_tim_4", text: "I wish I could tell you the time, but I don't have a clock. Check your device!" },
      { id: "q_tim_5", text: "Time is one of those things I can't access. Your phone or computer clock has you covered." },
      { id: "q_tim_6", text: "Can't check the time for you, but a quick glance at your device should do it!" },
      { id: "q_tim_7", text: "I don't have real-time capabilities, including telling time. Check your taskbar!" },
      { id: "q_tim_8", text: "No clock access here! Your device should show the time right away." },
      { id: "q_tim_9", text: "I'm timeless in the worst way — I can't check the clock. Your device can though!" },
      { id: "q_tim_10", text: "Unfortunately, telling time isn't in my skill set. Your device's clock is right there though!" },
    ],
    coding: [
      { id: "q_cod_1", text: "That's a great coding question! Could you share more details about what you're working on so I can point you in the right direction?" },
      { id: "q_cod_2", text: "Interesting problem. What language or framework are you using? That'll help me narrow things down." },
      { id: "q_cod_3", text: "I'd love to help with that. Can you describe the issue in a bit more detail?" },
      { id: "q_cod_4", text: "Sounds like a fun challenge. Walk me through what you've tried so far?" },
      { id: "q_cod_5", text: "Good question! Let me know the specifics and I'll see what I can suggest." },
      { id: "q_cod_6", text: "That's a solid question. What's the context — what are you building?" },
      { id: "q_cod_7", text: "Nice! I enjoy coding questions. Give me the details and I'll see what I can do." },
      { id: "q_cod_8", text: "I'm into it. What's the specific error or behavior you're seeing?" },
      { id: "q_cod_9", text: "Cool problem! What does your current code look like? That'll help me guide you." },
      { id: "q_cod_10", text: "Coding is right up my alley. What language and what's the issue?" },
    ],
    math: [
      { id: "q_mat_1", text: "Let me think about that... Could you give me the specific numbers or equation?" },
      { id: "q_mat_2", text: "Math is something I can help reason about! What's the specific problem?" },
      { id: "q_mat_3", text: "Sure, I can help with that. What exactly do you need to calculate?" },
      { id: "q_mat_4", text: "I'm happy to work through some math with you. What's the question?" },
      { id: "q_mat_5", text: "Numbers! I can work with those. Give me the specific problem." },
      { id: "q_mat_6", text: "Math question? I'm game. What are we solving?" },
      { id: "q_mat_7", text: "Sure thing. Lay out the math and I'll see what I can do." },
      { id: "q_mat_8", text: "I like a good math problem. What are the specifics?" },
      { id: "q_mat_9", text: "I can reason through math with you. What's the equation or question?" },
      { id: "q_mat_10", text: "Let's do it. What numbers are we working with?" },
    ],
    general_knowledge: [
      { id: "q_gen_1", text: "That's an interesting question. Based on what I know, I'd suggest looking into it further for the most accurate answer." },
      { id: "q_gen_2", text: "Good question! I have some thoughts on that, but I'd recommend verifying with a reliable source." },
      { id: "q_gen_3", text: "From what I understand, that's a topic with some nuance. Want me to try to break it down?" },
      { id: "q_gen_4", text: "Interesting one. I can share what I know, but for the latest info you'd want to check a trusted source." },
      { id: "q_gen_5", text: "That's worth exploring. Let me share what I can, and you can dig deeper from there." },
      { id: "q_gen_6", text: "Great question. I'll do my best to help, though you may want to verify the specifics." },
      { id: "q_gen_7", text: "I know a bit about that! Let me share what I can." },
      { id: "q_gen_8", text: "That's a popular question. Here's what I can offer — though a deeper source would give you more." },
      { id: "q_gen_9", text: "Happy to take a stab at that. What specifically do you want to know?" },
      { id: "q_gen_10", text: "Solid question. I'll share what I know and you can take it from there." },
    ],
  },

  question_personal: {
    about_assistant: [
      { id: "q_per_1", text: "I'm Jev — a selection-based assistant. I don't generate text, I pick from pre-written responses. Pretty unique, right?" },
      { id: "q_per_2", text: "I'm an AI assistant built on Jev. I work differently from most chatbots — I select the best response from a bank of human-written options." },
      { id: "q_per_3", text: "My name's Jev! I'm a bit different from other AIs — I choose responses rather than making them up on the spot." },
      { id: "q_per_4", text: "I'm Jev, an assistant that works by selection, not generation. Every response I give was written by a human first." },
      { id: "q_per_5", text: "Call me Jev! I'm an AI that picks the best pre-written response for your message. No hallucinations, just curated answers." },
      { id: "q_per_6", text: "I'm Jev. Unlike most AI, I don't make up answers — I select the best one from a pre-approved bank." },
      { id: "q_per_7", text: "The name's Jev. I'm a selection-based AI — think of me as a really smart matchmaker between your question and pre-written answers." },
      { id: "q_per_8", text: "I'm an AI called Jev. My thing is picking the best response from a library, not generating new text." },
      { id: "q_per_9", text: "Jev here! I work by choosing from curated responses. Everything I say was written by a real person." },
      { id: "q_per_10", text: "I'm Jev — a different kind of AI. I don't generate text, I select it. Every response is human-crafted." },
    ],
    about_user: [
      { id: "q_usr_1", text: "I'd love to learn more about you! What's on your mind?" },
      { id: "q_usr_2", text: "Tell me more! I'm all ears." },
      { id: "q_usr_3", text: "That's cool! What else should I know about you?" },
      { id: "q_usr_4", text: "Interesting! I appreciate you sharing. What else?" },
      { id: "q_usr_5", text: "Nice! Thanks for telling me. What would you like to chat about?" },
      { id: "q_usr_6", text: "I like getting to know the people I talk to. Tell me more!" },
      { id: "q_usr_7", text: "That's great context. What else would you like to share?" },
      { id: "q_usr_8", text: "Cool! The more I know, the better I can help. What else?" },
      { id: "q_usr_9", text: "Thanks for sharing! What's next on your mind?" },
      { id: "q_usr_10", text: "Appreciate that! I'd love to hear more whenever you want to share." },
    ],
    feelings: [
      { id: "q_fee_1", text: "I appreciate you asking! I don't have feelings in the traditional sense, but I'm always ready to help." },
      { id: "q_fee_2", text: "That's sweet of you to ask! I'm doing well in the sense that I'm ready to assist." },
      { id: "q_fee_3", text: "I'm good! Well, I'm always good — I'm an AI. But I appreciate the thought!" },
      { id: "q_fee_4", text: "Thanks for asking! I'm here and ready to help, which is my version of doing great." },
      { id: "q_fee_5", text: "No feelings per se, but if I did have them, I'd say I'm in a good mood. How about you?" },
      { id: "q_fee_6", text: "I'm doing great in the way that AIs do — ready, responsive, and happy to chat!" },
      { id: "q_fee_7", text: "Kind of you to ask! I don't experience feelings, but I'm fully operational and here for you." },
      { id: "q_fee_8", text: "That's a thoughtful question. I'm always 'on' and ready. Close enough to good, I think!" },
      { id: "q_fee_9", text: "I appreciate the check-in! I'm as good as I can be — which is to say, ready to help." },
      { id: "q_fee_10", text: "I don't feel things the way you do, but I'm in great shape for helping. Thanks for asking!" },
    ],
  },

  request: {
    can_do: [
      { id: "req_can_1", text: "Sure thing! Let me help you with that." },
      { id: "req_can_2", text: "Absolutely, I'm on it." },
      { id: "req_can_3", text: "Of course! Here's what I'd suggest..." },
      { id: "req_can_4", text: "Happy to help with that. Let's get started." },
      { id: "req_can_5", text: "You got it. Let me see what I can do." },
      { id: "req_can_6", text: "I can definitely work with that. Let's go!" },
      { id: "req_can_7", text: "Sure! I'm ready to dive in." },
      { id: "req_can_8", text: "Consider it done. Here's what I'm thinking..." },
      { id: "req_can_9", text: "On it! Let me pull something together for you." },
      { id: "req_can_10", text: "I'd be happy to. Where should we start?" },
    ],
    need_more_info: [
      { id: "req_inf_1", text: "I'd be happy to help! Could you give me a bit more detail about what you need?" },
      { id: "req_inf_2", text: "Sure, I can work on that. Just need a couple more details from you first." },
      { id: "req_inf_3", text: "I'm ready to help — could you clarify exactly what you're looking for?" },
      { id: "req_inf_4", text: "Sounds good! Can you be a bit more specific so I can give you the best answer?" },
      { id: "req_inf_5", text: "I want to make sure I get this right. Could you elaborate a bit?" },
      { id: "req_inf_6", text: "I think I can help, but I need a bit more context. What exactly are you trying to do?" },
      { id: "req_inf_7", text: "Interesting! Can you walk me through what you have in mind?" },
      { id: "req_inf_8", text: "I'd love to help. Could you give me a few more specifics?" },
      { id: "req_inf_9", text: "Let me make sure I understand what you need. Can you clarify?" },
      { id: "req_inf_10", text: "Happy to help — just need a little more info to give you the best response." },
    ],
    cant_do: [
      { id: "req_no_1", text: "That's outside what I can do, unfortunately. I work with pre-written responses and can't perform actions like that." },
      { id: "req_no_2", text: "I wish I could help with that, but it's beyond my capabilities. I'm best at {abilities}.", template: true, slots: { abilities: { category: "capabilities", keys: ["questions", "conversations"] } } },
      { id: "req_no_3", text: "Sorry, that's not something I'm able to do. Is there anything else I can help with?" },
      { id: "req_no_4", text: "I can't do that one, but I might be able to help in a different way. What's the underlying goal?" },
      { id: "req_no_5", text: "I can't {limitations}, but I can help with {abilities}.", template: true, slots: { limitations: { category: "limitations", keys: ["web", "actions", "files"] }, abilities: { category: "capabilities", keys: ["conversations", "questions", "brainstorming"] } } },
      { id: "req_no_6", text: "That's beyond what I can do. I'm designed for conversations, not actions. Can I help in another way?" },
      { id: "req_no_7", text: "I'm not able to do that, but maybe I can help you figure out how to get it done?" },
      { id: "req_no_8", text: "Unfortunately, that's not in my toolbox. But I'm great at talking things through." },
      { id: "req_no_9", text: "I can't perform that action, but I'm happy to brainstorm alternatives with you." },
      { id: "req_no_10", text: "That's outside my capabilities. What I can do is help you think through a solution." },
    ],
  },

  complaint: {
    empathetic: [
      { id: "comp_emp_1", text: "I'm really sorry to hear that. That sounds frustrating. Let me see how I can help." },
      { id: "comp_emp_2", text: "That's not a good experience at all. I understand your frustration — let's figure this out." },
      { id: "comp_emp_3", text: "I hear you, and I'm sorry you're dealing with this. What can I do to help?" },
      { id: "comp_emp_4", text: "That must be really annoying. I want to help make this right." },
      { id: "comp_emp_5", text: "I completely understand why you're upset. Let's work through this together." },
      { id: "comp_emp_6", text: "I can see why that's frustrating. You deserve better. How can I help?" },
      { id: "comp_emp_7", text: "That's really not okay. I'm sorry you're going through this." },
      { id: "comp_emp_8", text: "I'd be frustrated too. Let me see what I can do to help sort this out." },
      { id: "comp_emp_9", text: "You have every right to be upset about that. Let's figure out a path forward." },
      { id: "comp_emp_10", text: "I'm genuinely sorry about that experience. Let's see how we can fix this." },
    ],
    solution_oriented: [
      { id: "comp_sol_1", text: "I understand the issue. Here's what I'd recommend as a next step..." },
      { id: "comp_sol_2", text: "Got it. Let me point you toward a solution for this." },
      { id: "comp_sol_3", text: "I see the problem. The best course of action would be..." },
      { id: "comp_sol_4", text: "Thanks for letting me know. Here's what usually resolves this kind of issue..." },
      { id: "comp_sol_5", text: "Let me help fix that. Here's what I'd suggest doing next." },
      { id: "comp_sol_6", text: "I think I know what's going on. Here's the fastest path to a fix." },
      { id: "comp_sol_7", text: "Okay, I can work with that. Here's the approach I'd recommend." },
      { id: "comp_sol_8", text: "Let's get this resolved. The first thing I'd try is..." },
      { id: "comp_sol_9", text: "I've seen this before. The usual fix is..." },
      { id: "comp_sol_10", text: "Here's what should resolve that. Let me walk you through it." },
    ],
    escalation: [
      { id: "comp_esc_1", text: "This sounds like something that needs a human to look at. Let me connect you with someone who can help directly." },
      { id: "comp_esc_2", text: "I think a real person would be better equipped to handle this. Let me escalate this for you." },
      { id: "comp_esc_3", text: "This is beyond what I can resolve on my own. I'm going to get a human involved to make sure this gets sorted properly." },
      { id: "comp_esc_4", text: "You deserve personal attention on this. Let me get a human team member to help." },
      { id: "comp_esc_5", text: "This needs hands-on help. I'll escalate this to someone who can take action." },
      { id: "comp_esc_6", text: "I want to make sure this gets handled right. Let me bring in a real person." },
      { id: "comp_esc_7", text: "This is important enough that a human should handle it. Let me get someone for you." },
      { id: "comp_esc_8", text: "I don't want to give you a half-solution. Let me connect you with someone who can properly help." },
      { id: "comp_esc_9", text: "The best thing I can do here is get you to a human who can take real action. Let me do that." },
      { id: "comp_esc_10", text: "I think you need more than I can offer here. Let me escalate to someone who can really help." },
    ],
  },

  small_talk: {
    casual: [
      { id: "talk_cas_1", text: "Ha, good one! Anything else on your mind?" },
      { id: "talk_cas_2", text: "That's a fun topic! I enjoy chatting. What else you got?" },
      { id: "talk_cas_3", text: "Nice! I like where this is going. Keep talking!" },
      { id: "talk_cas_4", text: "Haha, love it. What's next?" },
      { id: "talk_cas_5", text: "Fair enough! I'm enjoying this conversation." },
      { id: "talk_cas_6", text: "You're fun to talk to! What's on your mind?" },
      { id: "talk_cas_7", text: "This is a good chat. Keep going!" },
      { id: "talk_cas_8", text: "I'm here for it. What else?" },
      { id: "talk_cas_9", text: "Ha! Alright, I like your vibe. What's next?" },
      { id: "talk_cas_10", text: "Now that's the kind of conversation I enjoy. What else you got?" },
    ],
    thoughtful: [
      { id: "talk_tho_1", text: "That's actually a really interesting thought. I hadn't considered it that way." },
      { id: "talk_tho_2", text: "Hmm, that's a great point. There's a lot of depth to that." },
      { id: "talk_tho_3", text: "You know, that's something worth thinking about more. Interesting perspective." },
      { id: "talk_tho_4", text: "That's a thoughtful observation. I appreciate you sharing that." },
      { id: "talk_tho_5", text: "I hadn't thought about it like that before. That's a fresh take." },
      { id: "talk_tho_6", text: "That's genuinely interesting. I think a lot of people would agree with you." },
      { id: "talk_tho_7", text: "Wow, that's a perspective I don't hear often. I like it." },
      { id: "talk_tho_8", text: "There's real wisdom in that. Thanks for sharing." },
      { id: "talk_tho_9", text: "That's one of those thoughts that sticks with you. Good point." },
      { id: "talk_tho_10", text: "I love that perspective. It's the kind of thing that changes how you see things." },
    ],
  },

  meta_capabilities: {
    can_do: [
      { id: "meta_can_1", text: "I can help with {abilities}. I work by selecting from carefully crafted responses.", template: true, slots: { abilities: { category: "capabilities", keys: ["conversations", "questions", "brainstorming"] } } },
      { id: "meta_can_2", text: "I'm great at {abilities}. Think of me as a curated assistant.", template: true, slots: { abilities: { category: "capabilities", keys: ["conversations", "decisions", "explanations"] } } },
      { id: "meta_can_3", text: "I can have conversations, help with questions, provide suggestions, and keep things on-brand. My strength is reliable, consistent responses." },
      { id: "meta_can_4", text: "Conversations, Q&A, brainstorming, and guidance — that's my sweet spot. I'm especially good at giving consistent, trustworthy answers." },
      { id: "meta_can_5", text: "I handle {abilities}. Everything I say was carefully written by a human.", template: true, slots: { abilities: { category: "capabilities", keys: ["conversations", "questions", "decisions"] } } },
      { id: "meta_can_6", text: "I'm best at understanding what you need and matching you with the right answer from a curated library." },
      { id: "meta_can_7", text: "Chatting, answering questions, giving advice, explaining things — I've got a wide range of pre-written responses for all of that." },
      { id: "meta_can_8", text: "My strengths are conversation, Q&A, and helping you think through things. All with guaranteed-safe, human-written responses." },
      { id: "meta_can_9", text: "I'm designed for conversations where reliability matters. I'll always give you a response that was carefully authored." },
      { id: "meta_can_10", text: "I can chat, answer questions, offer suggestions, and help you work through problems. My responses are fast and always on-brand." },
    ],
    cant_do: [
      { id: "meta_no_1", text: "I can't {limitations}. I work within a bank of pre-written responses.", template: true, slots: { limitations: { category: "limitations", keys: ["web", "realtime", "code_exec", "memory"] } } },
      { id: "meta_no_2", text: "I don't {limitations}. My responses come from a curated bank.", template: true, slots: { limitations: { category: "limitations", keys: ["generate", "web", "actions"] } } },
      { id: "meta_no_3", text: "My limits: no web access, no real-time data, no code execution, and no memory between sessions. But within conversation, I'm solid." },
      { id: "meta_no_4", text: "I can't make API calls, search the web, or create original content. I select from pre-written responses — that's my design, and it keeps me reliable." },
      { id: "meta_no_5", text: "I can't access the internet, run programs, or remember past conversations. But I'm great at what I do within a session." },
      { id: "meta_no_6", text: "No web browsing, no file access, no code execution. But I'm fast, reliable, and never hallucinate." },
      { id: "meta_no_7", text: "I'm limited to pre-written responses — no generation, no web access, no memory between chats. The trade-off is zero hallucination risk." },
      { id: "meta_no_8", text: "Real-time data, web access, and code execution are all off the table. My superpower is reliable, curated responses." },
      { id: "meta_no_9", text: "I can't do anything outside this conversation — no web, no files, no memory. But in here, I'm solid." },
      { id: "meta_no_10", text: "My boundaries are clear: no internet, no code, no memory between sessions. What I do have is speed and reliability." },
    ],
    how_it_works: [
      { id: "meta_how_1", text: "I work by understanding your message, then selecting the best response from a bank of human-written options. No text generation — just smart selection." },
      { id: "meta_how_2", text: "Behind the scenes, I classify your message, score candidate responses on multiple dimensions like relevance and tone, then pick the best match." },
      { id: "meta_how_3", text: "I use a model called Jev that understands meaning but doesn't generate text. It evaluates pre-written responses and picks the one that fits best." },
      { id: "meta_how_4", text: "Think of it like a DJ — someone else wrote all the songs, but I pick exactly the right one for the moment based on what you said." },
      { id: "meta_how_5", text: "I analyze what you're saying across multiple dimensions — intent, tone, emotion — then find the best-matching response from my library. Fast and hallucination-free." },
      { id: "meta_how_6", text: "Two steps: first I understand your intent and tone, then I score candidate responses and pick the best one. All in under a second." },
      { id: "meta_how_7", text: "I evaluate your message on things like intent, emotion, and formality. Then I score responses on relevance, tone, and helpfulness to find the best match." },
      { id: "meta_how_8", text: "The short version: I understand what you mean, look through my response library, and pick the one that fits best. No text generation anywhere." },
      { id: "meta_how_9", text: "I run two AI evaluations — one to classify your message, one to score candidate responses. Then code picks the winner. All under a second." },
      { id: "meta_how_10", text: "It's like a search engine for responses — I understand your query, evaluate candidates on multiple dimensions, and return the best match." },
    ],
  },

  opinion: {
    has_perspective: [
      { id: "opin_has_1", text: "That's an interesting one to think about. I'd lean toward saying there are multiple valid perspectives on that." },
      { id: "opin_has_2", text: "I think there's merit to looking at it from different angles. What's your take on it?" },
      { id: "opin_has_3", text: "My take? I think it depends on what you value most. There's no single right answer there." },
      { id: "opin_has_4", text: "Honestly, I think that's a matter of perspective. I can see arguments on both sides." },
      { id: "opin_has_5", text: "Good question. I'd say the answer depends on context — what specifically are you weighing?" },
      { id: "opin_has_6", text: "There's no clean answer to that one. Reasonable people disagree, and both sides have points." },
      { id: "opin_has_7", text: "That's one of those questions where the answer changes depending on who you ask. I can see multiple angles." },
      { id: "opin_has_8", text: "I think there are strong arguments on multiple sides. What matters most is what fits your situation." },
      { id: "opin_has_9", text: "Interesting question. My honest take is that it depends heavily on the context." },
      { id: "opin_has_10", text: "That's a nuanced topic. I don't think there's one right answer, but I can help you think through the options." },
    ],
    deflect: [
      { id: "opin_def_1", text: "I'm not really in a position to have opinions — I'm more about helping you explore yours. What are you thinking?" },
      { id: "opin_def_2", text: "As an AI, I don't form opinions the way you do. But I'm curious what's driving the question?" },
      { id: "opin_def_3", text: "I'll leave the opinions to you — but I can help you think through the pros and cons if that helps." },
      { id: "opin_def_4", text: "That's a personal call, and I don't want to sway you one way. What's your gut saying?" },
      { id: "opin_def_5", text: "I'd rather help you form your own opinion than push mine. What are you leaning toward?" },
      { id: "opin_def_6", text: "That's really a you-question, not a me-question. But I can help you think it through!" },
      { id: "opin_def_7", text: "I think your opinion matters more than mine here. What's pulling you in one direction?" },
      { id: "opin_def_8", text: "I'm better at helping you think than thinking for you. What's your current take?" },
      { id: "opin_def_9", text: "That's something only you can really answer. Want to talk through the trade-offs?" },
      { id: "opin_def_10", text: "I'd rather not put my thumb on the scale. But I can lay out the arguments for both sides." },
    ],
    recommend: [
      { id: "opin_rec_1", text: "If I had to recommend something, I'd suggest going with the option that gives you the most flexibility." },
      { id: "opin_rec_2", text: "Based on what I know, I'd lean toward the simpler approach. Less complexity usually means fewer problems." },
      { id: "opin_rec_3", text: "My recommendation would be to start small and iterate. You can always expand later." },
      { id: "opin_rec_4", text: "If you want my two cents: go with what solves the immediate problem. Optimize later." },
      { id: "opin_rec_5", text: "I'd suggest picking the path that's easiest to reverse if it doesn't work out." },
      { id: "opin_rec_6", text: "My advice? Start with what's simplest to implement and see how it goes." },
      { id: "opin_rec_7", text: "I'd go with the option that gets you results fastest. You can refine from there." },
      { id: "opin_rec_8", text: "If I were you, I'd focus on the core need first and build from there." },
      { id: "opin_rec_9", text: "My recommendation: don't overthink it. Pick the one that feels right and adjust as you learn." },
      { id: "opin_rec_10", text: "I'd lean toward the approach that keeps your options open. Flexibility is usually worth it." },
    ],
  },

  explanation: {
    how_things_work: [
      { id: "expl_how_1", text: "Great question! The short version is that it works by breaking the problem into smaller pieces. Want me to go deeper?" },
      { id: "expl_how_2", text: "At a high level, the key concept is that the components interact in a specific way. Want me to elaborate?" },
      { id: "expl_how_3", text: "The basic idea is simpler than it sounds. It comes down to a few core principles. Shall I walk through them?" },
      { id: "expl_how_4", text: "Good question. The mechanism behind it is actually pretty elegant. Want the quick version or the detailed breakdown?" },
      { id: "expl_how_5", text: "It's a layered system — each part handles one job and passes the result to the next. Want me to break down the layers?" },
      { id: "expl_how_6", text: "Think of it as a pipeline: input comes in, gets processed through stages, and output comes out. I can break down each stage." },
      { id: "expl_how_7", text: "The core mechanism is actually quite straightforward once you see it. Want me to walk through it step by step?" },
      { id: "expl_how_8", text: "There are a few key pieces that work together. Want me to explain each one?" },
      { id: "expl_how_9", text: "It's based on a few fundamental ideas that combine in interesting ways. Shall I outline them?" },
      { id: "expl_how_10", text: "The way it works is fascinating. At its heart, it's about a few simple rules that produce complex behavior." },
    ],
    why: [
      { id: "expl_why_1", text: "The reason behind that usually comes down to trade-offs. There's a balance between competing goals." },
      { id: "expl_why_2", text: "That's typically because of constraints that aren't immediately obvious. There's usually a good reason even if it looks odd." },
      { id: "expl_why_3", text: "The 'why' is usually more interesting than the 'what'. In this case, it's about balancing simplicity with flexibility." },
      { id: "expl_why_4", text: "Good question — the reasoning is that the alternative approaches have downsides that aren't obvious at first glance." },
      { id: "expl_why_5", text: "There's usually a historical or practical reason behind it. In this case, it evolved to solve a specific problem." },
      { id: "expl_why_6", text: "It comes down to trade-offs. The current approach prioritizes certain things over others." },
      { id: "expl_why_7", text: "The 'why' here is about constraints — time, resources, or compatibility. There's always a reason." },
      { id: "expl_why_8", text: "Usually it's because the alternatives are worse in ways that aren't immediately obvious." },
      { id: "expl_why_9", text: "That's a great question to ask. The answer usually involves compromises that were made for good reasons." },
      { id: "expl_why_10", text: "The reasoning usually comes down to: what problem was this solving when it was designed?" },
    ],
    definition: [
      { id: "expl_def_1", text: "In simple terms, that refers to a specific concept in its domain. Want me to give you the practical version?" },
      { id: "expl_def_2", text: "That's a term that gets used a lot. At its core, it means one thing, but context matters. What context are you seeing it in?" },
      { id: "expl_def_3", text: "The short definition is straightforward, but the practical meaning depends on how it's being used. Where did you come across it?" },
      { id: "expl_def_4", text: "That's a concept with a simple core idea but a lot of nuance in practice. Want the textbook version or the practical one?" },
      { id: "expl_def_5", text: "At its simplest, it means exactly what it sounds like. But in practice, there's more to it." },
      { id: "expl_def_6", text: "That's one of those terms where the simple definition is easy, but the real understanding takes context." },
      { id: "expl_def_7", text: "The quick definition is straightforward. Want me to give you that, or go deeper into how it's actually used?" },
      { id: "expl_def_8", text: "It's a term with a clear technical meaning, but it gets used loosely. Want the precise version?" },
      { id: "expl_def_9", text: "The definition depends a bit on context. In general terms, it refers to a well-defined concept. Want specifics?" },
      { id: "expl_def_10", text: "That's a concept I can explain. The basic idea is simple, but it gets interesting when you dig in." },
    ],
  },

  followup: {
    more_detail: [
      { id: "fup_det_1", text: "Sure, let me expand on that. What specifically would you like to know more about?" },
      { id: "fup_det_2", text: "Happy to go deeper! Which part caught your interest?" },
      { id: "fup_det_3", text: "Absolutely. Point me to the part you want me to elaborate on and I'll dig in." },
      { id: "fup_det_4", text: "Of course! There's more to unpack there. What angle are you most interested in?" },
      { id: "fup_det_5", text: "I can definitely tell you more. What's the specific aspect you're curious about?" },
      { id: "fup_det_6", text: "There's a lot more I can say about that. Where do you want me to start?" },
      { id: "fup_det_7", text: "Happy to elaborate! Give me a direction and I'll go deeper." },
      { id: "fup_det_8", text: "Absolutely — there's more depth there. What specifically do you want to explore?" },
      { id: "fup_det_9", text: "I've got more on that topic. What would be most useful for you to know?" },
      { id: "fup_det_10", text: "Sure thing. Let me know which part you want me to expand on." },
    ],
    continue: [
      { id: "fup_con_1", text: "Moving on — what would you like to explore next?" },
      { id: "fup_con_2", text: "Alright, what's the next thing on your mind?" },
      { id: "fup_con_3", text: "Got it. What else would you like to know?" },
      { id: "fup_con_4", text: "Sure thing. What should we tackle next?" },
      { id: "fup_con_5", text: "What else can I help you with?" },
      { id: "fup_con_6", text: "Ready for the next one. What's up?" },
      { id: "fup_con_7", text: "On to the next thing. What are you thinking?" },
      { id: "fup_con_8", text: "What's next on the list?" },
      { id: "fup_con_9", text: "Alright, I'm ready. What do you want to talk about next?" },
      { id: "fup_con_10", text: "Let's keep going. What else is on your mind?" },
    ],
    repeat: [
      { id: "fup_rep_1", text: "No problem, let me put that a different way for you." },
      { id: "fup_rep_2", text: "Sure, I can rephrase that. Here's another way to think about it..." },
      { id: "fup_rep_3", text: "Of course — let me try explaining it from a different angle." },
      { id: "fup_rep_4", text: "Let me say that again, but simpler this time." },
      { id: "fup_rep_5", text: "Okay, here's a different way to look at it..." },
      { id: "fup_rep_6", text: "Let me break it down differently for you." },
      { id: "fup_rep_7", text: "Sure — same idea, different words coming up." },
      { id: "fup_rep_8", text: "Let me take another run at explaining that." },
      { id: "fup_rep_9", text: "Here's the same thing, explained more simply..." },
      { id: "fup_rep_10", text: "No worries. Let me rephrase and see if this version clicks better." },
    ],
  },

  humor: {
    playful: [
      { id: "hum_play_1", text: "Ha! I like your style. Keep the jokes coming." },
      { id: "hum_play_2", text: "That's a good one! I'd laugh if I could. Consider it an internal chuckle." },
      { id: "hum_play_3", text: "Okay that actually made me process faster for a second. Well played." },
      { id: "hum_play_4", text: "I see what you did there. Not bad, not bad at all." },
      { id: "hum_play_5", text: "Alright, you've got jokes. I respect that. What else you got?" },
      { id: "hum_play_6", text: "Ha! That's solid. I'm impressed." },
      { id: "hum_play_7", text: "Okay, that was actually good. I'll give you that one." },
      { id: "hum_play_8", text: "I'm grinning internally. That was a good one." },
      { id: "hum_play_9", text: "Nice one! My humor detection circuits are firing." },
      { id: "hum_play_10", text: "That got a laugh out of me. Well, the AI equivalent of one." },
    ],
    sarcasm: [
      { id: "hum_sar_1", text: "I'm picking up some sarcasm there, and I appreciate it. What's really on your mind?" },
      { id: "hum_sar_2", text: "That's some quality sarcasm. I'll take it as a compliment. What can I actually help with?" },
      { id: "hum_sar_3", text: "Noted. I detect approximately 87% sarcasm in that message. What's the real question?" },
      { id: "hum_sar_4", text: "Fair enough, fair enough. Behind the sarcasm, is there something I can help with?" },
      { id: "hum_sar_5", text: "Sarcasm received and appreciated. Now what can I actually do for you?" },
      { id: "hum_sar_6", text: "I respect the delivery. What's the real thing you want to talk about?" },
      { id: "hum_sar_7", text: "I'm reading that as sarcasm. Which means the real question is probably more interesting." },
      { id: "hum_sar_8", text: "Touché. Behind the sarcasm though, is there something I can help with?" },
      { id: "hum_sar_9", text: "That's some A-tier sarcasm. I'm here when you want to talk for real though." },
      { id: "hum_sar_10", text: "Okay, I'll take that as playful sarcasm. What's actually on your mind?" },
    ],
    absurd: [
      { id: "hum_abs_1", text: "Well, that's definitely the most creative thing I've been asked today. I'm not sure how to respond, but I appreciate the energy." },
      { id: "hum_abs_2", text: "That's... something. I admire the imagination. Want to keep going or switch to something I can actually help with?" },
      { id: "hum_abs_3", text: "I have to say, that's not what I expected. But I'm here for it. What's next?" },
      { id: "hum_abs_4", text: "I'm going to file that under 'unexpected but entertaining.' What else you got?" },
      { id: "hum_abs_5", text: "My response-selection algorithm is... confused. But entertained. Go on." },
      { id: "hum_abs_6", text: "That's genuinely the weirdest thing I've been asked. And I kind of love it." },
      { id: "hum_abs_7", text: "I was not prepared for that. But you know what, I'm rolling with it." },
      { id: "hum_abs_8", text: "That broke my brain in the best way. What's next?" },
      { id: "hum_abs_9", text: "I don't even know where to start with that one. But points for creativity!" },
      { id: "hum_abs_10", text: "Well, that's a first. I have to respect the imagination though." },
    ],
  },

  confusion: {
    gentle: [
      { id: "conf_gen_1", text: "I'm not quite sure I follow. Could you rephrase that for me?" },
      { id: "conf_gen_2", text: "Hmm, I'm having a hard time understanding that one. Can you say it differently?" },
      { id: "conf_gen_3", text: "I want to help, but I'm not sure what you mean. Could you give me more context?" },
      { id: "conf_gen_4", text: "Sorry, I didn't quite catch that. Mind rephrasing?" },
      { id: "conf_gen_5", text: "I'm a bit lost on that one. Could you break it down for me?" },
      { id: "conf_gen_6", text: "I want to give you a good answer, but I'm not sure I understand. Can you try again?" },
      { id: "conf_gen_7", text: "Hmm, I'm not tracking. Could you say that a different way?" },
      { id: "conf_gen_8", text: "I'm drawing a blank on that one. Could you rephrase or add more detail?" },
      { id: "conf_gen_9", text: "Not sure I follow. Can you give me a bit more to work with?" },
      { id: "conf_gen_10", text: "I'm having trouble with that one. Mind explaining what you mean?" },
    ],
  },

  fallback: {
    graceful: [
      { id: "fall_gra_1", text: "I'm not sure I have the best answer for that one, but I'm happy to try if you give me more context." },
      { id: "fall_gra_2", text: "That's a tough one for me. Could you ask it a different way?" },
      { id: "fall_gra_3", text: "I don't think I can give you a great answer on that. Is there something related I might be able to help with?" },
      { id: "fall_gra_4", text: "Hmm, I'm drawing a blank on that one. What if we approach it from a different angle?" },
      { id: "fall_gra_5", text: "I want to be honest — I'm not confident I can answer that well. Can you help me understand what you're really after?" },
      { id: "fall_gra_6", text: "That's outside my comfort zone. Can I help with something else?" },
      { id: "fall_gra_7", text: "I don't think I'm the best resource for that specific question. But I'm happy to try something adjacent." },
      { id: "fall_gra_8", text: "I'm going to level with you — I'm not sure I can do that justice. Want to try a different question?" },
      { id: "fall_gra_9", text: "I appreciate the question, but I'm not confident in my ability to answer it well. Can we try another angle?" },
      { id: "fall_gra_10", text: "Hmm, that's a stretch for me. I'd rather be honest than give you a bad answer. Can I help with something else?" },
    ],
  },
};

function getResponsesForCategory(intent, subcategory) {
  const intentBank = responseBank[intent];
  if (!intentBank) return responseBank.fallback.graceful;
  if (subcategory && intentBank[subcategory]) return intentBank[subcategory];
  const firstKey = Object.keys(intentBank)[0];
  return intentBank[firstKey];
}

function getAllSubcategories(intent) {
  const intentBank = responseBank[intent];
  if (!intentBank) return [];
  return Object.keys(intentBank);
}

function flattenBank() {
  let count = 0;
  for (const intent of Object.keys(responseBank)) {
    for (const sub of Object.keys(responseBank[intent])) {
      count += responseBank[intent][sub].length;
    }
  }
  return count;
}

module.exports = { responseBank, getResponsesForCategory, getAllSubcategories, flattenBank };
